# Generated by Django 2.0.6 on 2020-10-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.SmallIntegerField(choices=[(0, 'male'), (2, 'other'), (1, 'famale')], default=0)),
                ('department', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
                'db_table': 'teacher_brf',
            },
        ),
    ]
