# Generated by Django 2.0.6 on 2020-10-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'famale'), (2, 'other'), (0, 'male')], default=0),
        ),
    ]
